The <b>Resonance Instrument Database</b> (ResonanceDB) aims to be a comprehensive and
powerful online database of free audio <b>samples</b> and <b>instrument</b>
sounds and also provide a place for users to share their own creations.
Currently supported file formats include: SoundFont 2, DLS and GigaSampler.
<p>
You are encouraged to
<a href="patches.py?Action=register">register</a> an account for additional
functionality including: post to forums, customize preferences and filters,
submit files, track files you have downloaded and comments you have made, rate
files and more. This database was created with 100% free
<a href="patches.py?Action=software">software</a> and is an extension of
<a href="http://swami.resonance.org">Project Swami</a>
- a collection of software projects for managing and editing instrument sounds.
<p>
We hope you enjoy <b>ResonanceDB</b> and invite you to send any comments,
suggestions, bug reports, or help requests to your admin and
programmer:
<p>
<a href="mailto:sounds-admin@resonance.org">Josh Green</a>
