<font class="title">Your account has been activated and you can now login.</font>
<p>
Welcome to the Resonance Instrument Database. An account has also been created
for you in the <a href="forums/">Forums</a> area with an identical login and password.
Currently the database and forum logins are separate. Once you login to your
forum account you may wish to edit your profile settings there as well to
customize your identity in the forums.
