Subject: Password reset for your Resonance Instrument Database account

This is an automated email message to notify you of your new password for your
account on the Resonance Instrument Database.  If you did not request a password
reset please notify the admin by email: sounds-admin@resonance.org

Please do not reply to this email, your response will likely be overlooked.
A real person can be contacted at the link above.

You can now login using the following:
Login: %(Login)s
Password: %(Password)s

After logging in, feel free to change your password to something more convenient
via your profile settings:
http://sounds.resonance.org/patches.py?Action=profile

    The Management
