The <b>Resonance Instrument Database</b> was created to provide a free
resource for instrument sounds.  In order to make use of extended
features, such as instrument submission, posting to forums, and
customization of your browsing experience its necessary to create an
account.  Accounts minimize abuses of the database and also facilitate
communication with other users.

<p>

<b>Our privacy pledge</b><br>

<ul>
<li>We will not give or sell your personal information to third
parties without your permission.</li>
<li>We will strive to give you the greatest control of what information you
desire to be publicly viewable.</li>
<li>Your email address will only be used to contact you about your account,
should the need arise, and any other communications you enable (such as forum
notification, message forwarding, comments on your instruments, mailing lists,
news letters, etc).  These features can be disabled at any time.</li>
<li>We will never send you spam or any other processed meat products.</li>
<li>We will do our best to ensure that you are a happy user and feel
a "Warm fuzzy feeling inside" (TM).</li>
</ul>

<p>

In summary: this system is here for you and we would never compromise this
relationship by being greedy little bastards.
<p>
Sincerely, The Mgt.
