<b>Password</b> - Choose a password (5-32 characters) or leave blank to keep current one.<br>
<b>Email</b> - Enter your email address. A valid email account is required
and can be used to retrieve your password in the event that you can't remember it.<br>
<b>User name</b> - Optional - Your name as you would like it to appear to others. This
can be any name you want. If not supplied, your login will be used.<br>
<b>Real name</b> - Optional - Your real name. You can choose who can view this information
with the <i>Real name visible</i> option.<br>
<b>Website</b> - Optional - Your web site.<br>
<b>Email visible</b> - Sets who can see your email address. 'No' will allow no one to see
your email address (except admins), but you can still receive messages to your account.
'Users' will allow any registered user to see your email address. 'All' will allow everyone
to see your email address, although it will be munged for anonymous users to try and
prevent automated spam bots from snarfing it.<br>
<b>Real name visible</b> - Sets who can see your real name. 'No' to allow no one but admins,
'Users' to allow only registered users, 'All' to allow everyone.<br>
<b>Options</b> - <i>Email me news:</i> If enabled, you will be subscribed to the Resonance
Instrument Database newsletter (very low traffic). <i>Notify on rating:</i> Notify, by email,
when a user comments or rates one of your instruments.<br>
