Subject: Activate your Resonance Instrument Database account

This is an automated email message in response to your recent registration
to the Resonance Instrument Database:
http://sounds.resonance.org

Welcome! To activate your account use the following link:
http://sounds.resonance.org/patches.py?Action=confirm&Login=%(Login)s&HashKey=%(HashKey)s

Please do not reply to this email, your response will likely be overlooked.
To contact a real person, the admin, use the following email address:
sounds-admin@resonance.org

We hope you find this service useful and invite you to participate to the extent
that you feel inspired to.  Have a nice day :)

    The Management
