Subject: Confirm request to reset your Resonance Instrument Database password

This is an automated email message in response to your request to reset your
password for your Resonance Instrument Database account.  If you did not make
this request, please ignore this message and consider notifying the admin:
sounds-admin@resonance.org.

Feel free to contact the admin for other reasons as well, but please do not
reply to THIS automated email, since your response will likely be overlooked.

To reset your password use the following link:
http://sounds.resonance.org/patches.py?Action=confirm&Login=%(Login)s&HashKey=%(HashKey)s

After resetting your password you will receive another email with the new
randomly generated password which you can change after logging in.

    The Management
