The Resonance Instrument Database has been made possible by many free software
projects.  Below is a list, although likely incomplete, of software and
individuals that helped in one way or another.

<table border=0 cellpadding=8 cellspacing=2 width="100%">
<tr><td colspan="2" align="center">
<h2>Instrument Software</h2>
<hr>
</td></tr>
<tr>
<td>
<a href="http://swami.resonance.org">
<img src="images/swami.png" alt="Project Swami" width=120 height=47 border=0>
</a>
</td>
<td>
Swami is a collection of instrument editing and management software projects
by the same author of ResonanceDB. libInstPatch (an instrument editing software
library) is used for importing and compressing patch files using its Python
binding.
</td>
</tr>
<tr>
<td>
<a href="http://swami.resonance.org/trac/wiki/CRAM">
<img src="images/cram_mini_banner.png" alt="CRAM" width=88 height=32 border=0>
</a>
</td>
<td>
Compress hybRid Audio Media is a standard for compressing files containing
audio and binary data and is also part of Project Swami.
</td>
</tr>
<tr><td colspan="2" align="center">
<h2>Image Software</h2>
<hr>
</td></tr>
<tr>
<td>
<a href="http://www.gimp.org/">
<img src="images/gimp.png" alt="The Gimp" width=90 height=36 border=0></a>
</td>
<td>
The Gimp is the de-facto standard of free raster image editing applications and
was used in creating/editing many of the images on this site.
</td>
</tr>
<tr>
<td>
<a href="http://www.blender3d.org/">
<img src="images/blender.jpg" alt="Blender" width=95 height=50 border=0></a>
</td>
<td>
Blender is a powerful multi-platform 3D modeling/rendering application used
for creating the tuning fork and some lighting effects in the ResonanceDB logo and
for rendering most of the category icons and modeling a few.
</td>
</tr>
<tr>
<td>
<a href="http://www.inkscape.org/">
<img src="images/inkscape.png" alt="Inkscape" width=100 height=100 border=0></a>
</td>
<td>
Inkscape is a nice vector graphics editing application which was used to
create the rating stars, some category icons and some other images.
</td>
</tr>
<tr><td colspan="2" align="center">
<h2>Hosting Software</h2>
<hr>
</td></tr>
<tr>
<td>
<a href="http://www.apache.org/">
<img src="images/apache.png" alt="Apache" width=148 height=40 border=0></a>
</td>
<td>
The Apache server is an HTTP web server which runs most of the Internet
including this server.
</td>
</tr>
<tr>
<td>
<a href="http://www.mysql.com/">
<img src="images/mysql.png" alt="MySQL" width=88 height=46 border=0></a>
</td>
<td>
MySQL is a very popular and powerful SQL database server which houses all the
instrument and user data for ResonanceDB.
</td>
</tr>
<tr>
<td>
<a href="http://www.python.org/">
<img src="images/python.png" alt="Python" width=105 height=60 border=0></a>
</td>
<td>
Python is a programming language and is what this instrument database
is programmed in.
</td>
</tr>
<tr>
<td>
<a href="http://www.modpython.org/">
<img src="images/modpython.png" alt="mod_python" width=120 height=83 border=0></a>
</td>
<td>
mod_python is a module for the Apache web server that makes it easy to
create web applications written in the Python scripting language.
</td>
</tr>
<tr><td colspan="2" align="center">
<h2>Additional Credits</h2>
<hr>
</td></tr>
<tr>
<td><img src="images/linux.png" alt="Linux" width=80 height=108 border=0></td>
<td>The Linux operating system is used on the author's desktop and also
runs this server.
</td>
</tr>
<tr>
<td><a href="http://www.3dcafe.com">
<img src="images/3dcafe.png" alt="3D Cafe" width=159 height=40 border=0></a></td>
<td>Most of the 3D models used for the category icons came from 3D Cafe's
<a href="http://www.3dcafe.com">Musical Instruments</a>
section (seems to require registration now?).</td>
</tr>
</table>
